// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Diff.Match.Patch")>]
[<assembly: AssemblyProductAttribute("Diff.Match.Patch")>]
[<assembly: InternalsVisibleToAttribute("Diff.Match.Patch.Tests")>]
[<assembly: AssemblyVersionAttribute("2.0.2")>]
[<assembly: AssemblyFileVersionAttribute("2.0.2")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Diff.Match.Patch"
    let [<Literal>] AssemblyProduct = "Diff.Match.Patch"
    let [<Literal>] InternalsVisibleTo = "Diff.Match.Patch.Tests"
    let [<Literal>] AssemblyVersion = "2.0.2"
    let [<Literal>] AssemblyFileVersion = "2.0.2"
    let [<Literal>] AssemblyInformationalVersion = "2.0.2"
